# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a1d7ba61655f9c8fa17b9092fecfe86b7f1698530cc413bc657c89f7e53a5a389466151e34787a354c39c5d1191bac80767652e05829c48d17e5ee506465230
  aws_access_key_id: <%= ENV["CLIENT_ID"] %>
  aws_secret_key: <%= ENV["CLIENT_SECRET"] %>
  associate_tag: <%= ENV["REFRESH_TOKEN"] %>
  
test:
  secret_key_base: 7970a36aeb41b93d3ffb7875b774d39179092426d5fed2b2381d97a6dc8e0e861a086abbdf3c140ba892ed38732798180347b966a4688b063b0197d5df87b703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["CLIENT_ID"] %>
  aws_secret_key: <%= ENV["CLIENT_SECRET"] %>
  associate_tag: <%= ENV["REFRESH_TOKEN"] %>